export type PlaylistItem = {
  adType: number;
  artists: null;
  backgroundCoverId: number;
  backgroundCoverUrl: null;
  cloudTrackCount: number;
  commentThreadId: string;
  coverImgId: number;
  coverImgId_str: string;
  coverImgUrl: string;
  createTime: number;
  creator: {
    accountStatus: number;
    anchor: boolean;
    authStatus: number;
    authenticationTypes: number;
    authority: number;
    avatarDetail: null;
    avatarImgId: number;
    avatarImgIdStr: string;
    avatarImgId_str: string;
    avatarUrl: string;
    backgroundImgId: number;
    backgroundImgIdStr: string;
    backgroundUrl: string;
    birthday: number;
    city: number;
    defaultAvatar: false;
    description: string;
    detailDescription: string;
    djStatus: number;
    expertTags: null;
    experts: null;
    followed: false;
    gender: number;
    mutual: false;
    nickname: string;
    province: number;
    remarkName: null;
    signature: string;
    userId: number;
    userType: number;
    vipType: number;
  };
  description: null;
  englishTitle: null;
  highQuality: false;
  id: number;
  name: string;
  newImported: boolean;
  opRecommend: boolean;
  ordered: boolean;
  playCount: number;
  privacy: number;
  recommendInfo: null;
  shareStatus: null;
  sharedUsers: null;
  specialType: number;
  status: number;
  subscribed: boolean;
  subscribedCount: number;
  subscribers: [];
  tags: [];
  titleImage: number;
  titleImageUrl: null;
  totalDuration: number;
  trackCount: number;
  trackNumberUpdateTime: number;
  trackUpdateTime: number;
  tracks: null;
  updateFrequency: null;
  updateTime: number;
  userId: number;
};

export type MusicDetail = {
  a: null;
  al: {
    id: number;
    name: string;
    pic: number;
    picUrl: string;
    pic_str: string;
    tns: [];
  };
  alia: [];
  ar: [
    {
      alias: [];
      id: number;
      name: string;
      tns: [];
    }
  ];
  cd: string;
  cf: string;
  copyright: number;
  cp: number;
  crbt: null;
  djId: number;
  dt: number;
  entertainmentTags: null;
  fee: number;
  ftype: number;
  h: { br: number; fid: number; size: number; vd: number; sr: number };
  hr: null;
  id: number;
  key?: number;
  l: { br: number; fid: number; size: number; vd: number; sr: number };
  m: { br: number; fid: number; size: number; vd: number; sr: number };
  mark: number;
  mst: number;
  mv: number;
  name: string;
  no: number;
  noCopyrightRcmd: null;
  originCoverType: number;
  originSongSimpleData: null;
  pop: number;
  pst: number;
  publishTime: number;
  resourceState: true;
  rt: string;
  rtUrl: null;
  rtUrls: [];
  rtype: number;
  rurl: null;
  s_id: number;
  single: number;
  songJumpInfo: null;
  sq: { br: number; fid: number; size: number; vd: number; sr: number };
  st: number;
  t: number;
  tagPicList: null;
  v: number;
  version: number;
};
export type Personalized = {
  alg: string;
  canDislike: boolean;
  copywriter: string;
  highQuality: boolean;
  id: number;
  name: string;
  picUrl: string;
  playCount: number;
  trackCount: number;
  trackNumberUpdateTime: number;
  type: number;
};

export type SearchHotItem = {
  alg: string;
  content: string;
  iconType: number;
  iconUrl: string;
  score: number;
  searchWord: string;
  source: number;
  url: string;
};

export type Profile = {
  accountStatus: number;
  allSubscribedCount: number;
  artistIdentity: null;
  authStatus: number;
  authority: number;
  avatarDetail: null;
  avatarImgId: number;
  avatarImgIdStr: string;
  avatarImgId_str: string;
  avatarUrl: string;
  backgroundImgId: number;
  backgroundImgIdStr: string;
  backgroundUrl: string;
  birthday: number;
  blacklist: boolean;
  cCount: number;
  city: number;
  createTime: number;
  defaultAvatar: boolean;
  description: string;
  detailDescription: string;
  djStatus: number;
  eventCount: number;
  expertTags: null;
  experts: {};
  followMe: boolean;
  followTime: null;
  followed: boolean;
  followeds: number;
  follows: number;
  gender: number;
  inBlacklist: boolean;
  mutual: boolean;
  newFollows: number;
  nickname: string;
  playlistBeSubscribedCount: number;
  playlistCount: number;
  privacyItemUnlimit: null;
  province: number;
  remarkName: null;
  sCount: number;
  sDJPCount: number;
  signature: string;
  userId: number;
  userType: number;
  vipType: number;
};
